name: GameSpot News

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */3 * * *"

jobs:
  fetch-news:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: actions/cache@v4
        with:
          path: data/sent-links.json
          key: gamespot-news-cache
          restore-keys: |
            gamespot-news-cache

      - run: npm install

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node src/index.js