name: GameSpot News

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - run: node src/index.js

      - name: Upload News JSON
        uses: actions/upload-artifact@v4
        with:
          name: latest-gamespot-news
          path: latest-news.json